
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>home page</title>
    <link rel="stylesheet" href="home.css">
</head>
<body>
<div class="topnav">
  <a class="active" href="p2.html" target="bottom">Home</a>
  <a href="insert.php" target="bottom">Insert</a>
  <a href="show.php" target="bottom">Show</a>
</div>
<h1>DBMS INNOVATIVE ASSIGNMENT</h1>

<H2> STUDENT HELPER SYSTEM</H2>

<p>
<B>IN THIS PARTICULAR STUDENT HEPLER SYSTEM, THE USER CAN ACCESS A LOTS OF VARIETY OF QUESTIONS ALL AROUND
THE WEB, AND HAS ALSO THE ACCESS TO STORE THE QUESTIONS WHICH CAME ACROSS THEM ON THE WEB FOR FUTURE USE.</p>


<UL>
THE NAVIGATION BAR ABOVE CAN PERFORM ALL OF THE FEATURES AS SAID:<br><br>
<LI>HOME PANE: THE DESCRIPTION OF ALL THE FEATURES OF THIS STUDENT HELPER SYSTEM.</LI>
<LI>INSERT PANE: THIS PANE ALLOWS YOU TO INSERT AS MANY AS QUESTIONS YOU COME ACROSS AROUND THE WEB IN OUR DATABASE</LI>
<LI>SHOW PANE: THIS PANE CAN BE HELPFUL WHENEVER YOU NEED TO SOLVE ANY KIND OF QUESTIONS FROM OUR HUGE DATABASE CLASSIFIED BY THEIR TOPIC AND DIFFICULTY</LI>
<LI>ABOUT PANE: A BRIEF DESCRIPTION OF THE CREATORS OF THIS STUDENT HEPLER SYSTEM</LI>
</UL>

</B>
</body>
</html>